[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Joshua A. <joshua.auchincloss@proton.me>"]
description = "ml model registry"
documentation = "https://github.com/joshua-auchincloss/flymodel"
edition = "2021"
homepage = "https://github.com/joshua-auchincloss/flymodel"
license = "AGPLv3 AND MIT AND BSD-2-Clause"
repository = "https://github.com/joshua-auchincloss/flymodel"
rust-version = "1.74.0"
version = "0.1.0"

[workspace.dependencies]
actix = "0.13.1"
dotenv = "0.15.0"
actix-web = "4.4.0"
anyhow = "1.0.75"
async-graphql = "6.0.11"
async-graphql-actix-web = "6.0.11"
async-trait = "0.1.74"
chrono = "0.4.31"
clap = "4.4.10"
futures-util = "0.3.29"
sea-orm = "0.12.7"
sea-orm-migration = "0.12.6"
serde = "1.0.193"
serde_json = "1.0.108"
serde_yaml = "0.9.27"
thiserror = "1.0.50"
tokio = "1.34.0"
tracing = "0.1"
tracing-subscriber = "0.3.18"
tracing-actix-web = "0.7.9"
opentelemetry = "0.21.0"
opentelemetry-otlp = "0.14.0"
opentelemetry_sdk = "0.21.1"
tonic = "0.9.2"
opentelemetry-semantic-conventions = "0.13.0"
bytes = "1.5.0"
aws-config = "1"
aws-sdk-s3 = "1"
aws-smithy-runtime-api = "1"


# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.5.0"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["shell", "powershell", "homebrew", "msi"]
# A GitHub repo to push Homebrew formulas to
tap = "flymodel/brew-tap"
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
    "x86_64-unknown-linux-musl",
    "x86_64-pc-windows-msvc",
    "i686-pc-windows-msvc",
]
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# Publish jobs to run in CI
pr-run-mode = "plan"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
