[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Joshua A. <joshua.auchincloss@proton.me>"]
description = "ml model registry"
documentation = "https://github.com/joshua-auchincloss/flymodel"
edition = "2021"
homepage = "https://github.com/joshua-auchincloss/flymodel"
license = "AGPLv3 AND MIT AND BSD-2-Clause"
repository = "https://github.com/joshua-auchincloss/flymodel"
rust-version = "1.74.0"
version = "0.1.0"

[workspace.dependencies]
actix = "0.13.1"
actix-web = "4.4.0"
anyhow = "1.0.75"
async-graphql = "6.0.11"
async-graphql-actix-web = "6.0.11"
async-trait = "0.1.74"
chrono = "0.4.31"
clap = "4.4.10"
futures-util = "0.3.29"
sea-orm = "0.12.7"
sea-orm-migration = "0.12.6"
serde = "1.0.193"
serde_json = "1.0.108"
serde_yaml = "0.9.27"
thiserror = "1.0.50"
tokio = "1.34.0"
tracing = "0.1"
tracing-subscriber = "0.3.18"
tracing-actix-web = "0.7.9"
