services:
  minio:
    container_name: minio
    volumes:
      - ./tmp/minio:/data
    ports:
      - 9000:9000
      - 9090:9090
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"

  pg:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
