version: '3'

tasks:
  env:
    cmds:
    - docker-compose up

  schema:
    cmds:
    - cynic introspect http://localhost:9009/graphql -o crates/graphql/schema/flymodel.graphql

  schema_diff:
    cmds:
    - cp crates/graphql/schema/flymodel.graphql crates/graphql/schema/flymodel.graphql.bk
    - task schema
    - diff -bB crates/graphql/schema/flymodel.graphql.bk crates/graphql/schema/flymodel.graphql
