version: '3'
includes:
  hurl:
    taskfile: ./hurl/Taskfile.yaml
    dir: hurl

tasks:
  env:
    cmds:
    - docker-compose up

  schema:
    cmds:
    - cynic introspect http://localhost:9009/graphql -o crates/graphql/schema/flymodel.graphql

  schema_diff:
    cmds:
    - cp crates/graphql/schema/flymodel.graphql crates/graphql/schema/flymodel.graphql.bk
    - task schema
    - diff -bB crates/graphql/schema/flymodel.graphql.bk crates/graphql/schema/flymodel.graphql

  visualize-schema:
    cmds:
    - docker run --rm -v ./vis/:/output/diagrams/ -it schemaspy/schemaspy:latest -host host.docker.internal -port 5432 --user postgres --password postgres -db mlops -imageformat png -renderer :cairo -t pgsql
    - convert ./vis/summary/relationships.real.large.png -gravity South -chop 0x45 ./docs/rels.png
    - rm -rf ./vis

  alpine:
    cmds:
    - docker build -f ./docker/alpine.Dockerfile -t flymodel:latest-alpine .

  integrity:
    cmds:
    - cmd: cargo migrate-down
      silent: true
    - cmd: cargo migrate-up --test-data multi_region
      silent: true
    - task: hurl:multi-region
    - cmd: cargo migrate-down
      silent: true
    - cmd: cargo migrate-up --test-data basic
      silent: true
    - task: hurl:single-region
    - cmd: cargo migrate-down
      silent: true
