version: '3'

tasks:
  wasm-clients:
    cmds:
    - wasm-pack build --target web --out-name index --features wasm-web
    - wasm-pack pack
    - cp -r ./pkg/* ../../clients/flymodel-web/
    - wasm-pack build --target nodejs --out-name index --features wasm-node
    - wasm-pack pack
    - cp -r ./pkg/* ../../clients/flymodel-node/

  test-wasm:
    cmds:
    - wasm-pack test --node --features wasm-node

  test-sys:
    cmds:
    - cargo test --package flymodel-client

  test:
    cmds:
    - task: test-wasm
    - task: test-sys
