[badges]
maintenance = {status = "actively-developed"}

[dependencies]
async-graphql = {workspace = true, features = [
  "tracing",
  "decimal",
  "chrono",
  "dataloader",
  "dynamic-schema"
]}
flymodel = {path = "../flymodel"}
juniper = "0.15.11"
lazy_static = "1.4.0"
sea-orm = {workspace = true, features = ["chrono"]}

[dependencies.sea-orm-migration]
features = ["runtime-tokio-native-tls", "sqlx-postgres"]
workspace = true
serde.workspace = true
thiserror.workspace = true

[features]

[package]
name = "flymodel-entities"
readme = "README.md"
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true

[package.metadata.release]
shared-version = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
