[alias]
build_cli = "build --package flymodel-cli --bin flymodel"
cli = "run --package flymodel-cli --bin flymodel"
migrate-down = "cli migrate down --config ./conf/flymodel.toml"
migrate-up = "cli migrate up --config ./conf/flymodel.toml"
serve = "cli serve --config ./conf/flymodel.toml"
serve-tls = "cli serve --config ./conf/flymodel-tls.toml"
storage = "cli setup-storage --config ./conf/flymodel.toml"
yamlconf = "cli setup-storage --config ./conf/flymodel.yaml"

[target.aarch64-apple-darwin]
rustflags = [
  "-C",
  "link-arg=-undefined",
  "-C",
  "link-arg=dynamic_lookup",
  "-C",
  "link-args=-L/usr/local/opt/llvm/lib,-I/usr/local/opt/llvm/include",
  "-C",
  "link-args=-Wl,-rpath,/Library/Developer/CommandLineTools/Library/Frameworks"
]

[target.x86_64-apple-darwin]
rustflags = [
  "-C",
  "link-arg=-undefined",
  "-C",
  "link-arg=dynamic_lookup",
  "-C",
  "link-args=-L/usr/local/opt/llvm/lib,-I/usr/local/opt/llvm/include",
  "-C",
  "link-args=-Wl,-rpath,/Library/Developer/CommandLineTools/Library/Frameworks"
]
