version: '3'
set: [pipefail]

vars:
  FLAGS: --verbose --noproxy localhost --http2

tasks:
  multi-region:
    dir: multi-region
    cmds:
    - hurl {{ .FLAGS }} ./namespace.hurl

  single-region:
    dir: single-region
    cmds:
    - hurl {{ .FLAGS }} ./namespace.hurl
    - hurl {{ .FLAGS }} ./experiment.hurl
    - hurl {{ .FLAGS }} ./model_artifact.hurl
