version: '3'
set: [pipefail]

tasks:
  multi-region:
    dir: multi-region
    cmds:
    - hurl ./namespace.hurl

  single-region:
    dir: single-region
    cmds:
    - hurl ./namespace.hurl
    - hurl ./experiment.hurl
    - hurl ./model_artifact.hurl
