[badges]
maintenance = { status = "actively-developed" }

[dependencies]
cynic = { version = "3", features = ["http-surf"] }
surf = "2"

[build-dependencies]
cynic-codegen = { version = "3", features=["rkyv"] }
insta = "1"


[features]

[package]
name = "flymodel-graphql"
readme = "README.md"
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true

[package.metadata.release]
shared-version = true
repository.workspace = true
rust-version.workspace = true
