name: Test

on:
  pull_request:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linux_target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v3

      - name: Setup Temp Data
        run: |
          mkdir -p ./tmp/postgres
          mkdir -p ./tmp/minio

      - uses: actions/cache@v3
        with:
          path: |
            target/
          key: ${{ hashFiles('crates/**') }}

      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: ./docker-compose.yaml

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.74.0
          components: rustfmt
          target: ${{ matrix.linux_target }}

      - name: Install tools
        run: |
          apt-get install -y libpq-dev

      - name: Pre Build & Cache
        run: |
          cargo build

      - name: Test Migration Up
        run: |
          cargo migrate-up --test-data multi_region

      - name: Test
        run: |
          cargo test --all-features

      - name: Test Migration Down
        run: |
          cargo migrate-down

      - name: Clean Temp Data
        run: |
          rm -rf ./tmp
