name: Test

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Setup Temp Data
      run: |
        rm -rf ./tmp
        mkdir -p ./tmp/postgres
        mkdir -p ./tmp/minio
        mkdir -p ./tmp/fs
        chmod -R g+rwx ./tmp

    - name: Install tools
      if: startsWith(matrix.os, 'macos-')
      run: |
        brew install --cask docker
        brew install protobuf libpq
        open -a Docker

    - uses: actions/cache@v3
      with:
        path: |
          target/
          crates/
          Cargo.toml
          docker-compose.yaml
          dev/
        key: ${{ hashFiles('crates/**') }}

    - name: Install Task
      uses: arduino/setup-task@v1

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.75.0
        components: rustfmt
        cache: false

    - name: Install Hurl
      uses: gacts/install-hurl@v1

    - name: Install cargo tools
      run: |
        cargo install --locked cynic-cli

    - name: Install tools
      if: startsWith(matrix.os, 'ubuntu-')
      run: |
        sudo apt-get install -y \
          libpq-dev \
          protobuf-compiler

    - name: Pre Build & Cache
      run: |
        RUSTFLAGS="-Awarnings" cargo build

    - uses: isbang/compose-action@v1.5.1
      with:
        compose-file: ./docker-compose.yaml

    - name: Wait for database start
      run: |
        while ! nc -z localhost 5432; do
          sleep 0.5
        done

        # sleep an extra 5s just in case
        sleep 5

    - name: Test Migration Up (basic)
      run: |
        target/debug/flymodel migrate up --test-data basic

    - name: Startup Server & Validate Introspection
      run: |
        set -euxo pipefail
        target/debug/flymodel serve  --config ./conf/flymodel.toml &
        sleep 10
        task schema_diff

    - name: Test Migration Down
      run: |
        target/debug/flymodel migrate down

    - name: Test Migration Up (multi-region)
      run: |
        target/debug/flymodel migrate up --test-data multi_region

    - name: Unit Tests (multi-region)
      run: |
        cargo test --all-features

    - name: Integrity Tests
      run: |
        task integrity

    - name: Test Migration Down
      run: |
        target/debug/flymodel migrate down
