name: Check and Lint

on:
  pull_request:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linux_target:
        - aarch64-unknown-linux-gnu
        - aarch64-unknown-linux-musl
        - x86_64-unknown-linux-gnu
        - x86_64-unknown-linux-musl

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          target/
        key: ${{ hashFiles('crates/**') }}

    - uses: isbang/compose-action@v1.5.1
      with:
        compose-file: ./docker-compose.yaml

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.75.0
        components: rustfmt
        target: ${{ matrix.linux_target }}
        default: true

    - name: Install tools
      run: |
        yum install -y epel-release
        yum install -y clang-devel clang lld

    - name: Test
      run: |
        cargo test
